version: '2'
services:
  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - ~/backups/zabbix:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=examplepassword
    restart: always
  zabbix-server:
    image: monitoringartist/zabbix-xxl:latest
    depends_on:
      - zabbix-db
    ports:
      - "80:80"
      - "443:443"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./alertscripts:/usr/local/share/zabbix/alertscripts
      - ./certificates:/usr/local/share/zabbix/ssl/certs
      - ./certificate_keys:/usr/local/share/zabbix/ssl/keys
      - ./nginx/nginx.conf:/etc/nginx/hosts.d/default.conf
    links:
      - zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=examplepassword
    restart: always
volumes:
  zabbix-db-storage:
    driver: local
